# Generated by Django 4.1.7 on 2023-04-19 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='bloom_taxonomy',
        ),
        migrations.AddField(
            model_name='question',
            name='question_difficulty',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
