# Generated by Django 4.2 on 2023-04-21 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_question_question_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_difficulty',
            new_name='question_models',
        ),
    ]
